name = 'fortsa'
version = '0.0.3'
maintainer = 'fortsa contributors'
license = 'BSD 3- Clause'
author = '左志华'
categories = 'time series analysis'
copyright = "2021 fortsa contributors"

[build]
auto-examples = false
auto-executables = false
auto-tests = false

[dependencies]
ctsa = { git="https://github.com/zoziha/ctsa", branch="ctsa-fpm" }

[dev-dependencies]
## `stdlib` inside `forlab` dependencies
forlab = { git = "https://github.com/fortran-fans/forlab", branch = "forlab-fpm" }
test-drive = { git="https://github.com/fortran-lang/test-drive" }

[library]
source-dir="src"

# ============================ tests ===========================================
## [dwt] tests
[[test]]
name="dwt_dwt"
source-dir="tests/dwt"
main="test_dwt_dwt.f90"
## [model] tests
[[test]]
name="model_ar"
source-dir="tests/model"
main="test_model_ar.f90"
[[test]]
name="model_ar2"
source-dir="tests/model"
main="test_model_ar2.f90"
[[test]]
name="model_arima"
source-dir="tests/model"
main="test_model_arima.f90"
[[test]]
name="model"
source-dir="tests/model"
main="checker.f90"
[[test]]
name="model_autoarima3"
source-dir="tests/model"
main="test_model_autoarima3.f90"
# [[test]]
# name="model_misc"
# source-dir="tests/model"
# main="test_model_misc.f90"
[[test]]
name="model_sarima"
source-dir="tests/model"
main="test_model_sarima.f90"
[[test]]
name="model_sarimax"
source-dir="tests/model"
main="test_model_sarimax.f90"
[[test]]
name="model_sarimax2"
source-dir="tests/model"
main="test_model_sarimax2.f90"
[[test]]
name="model_sarimax3"
source-dir="tests/model"
main="test_model_sarimax3.f90"

## [stats] tests
[[test]]
name="stats"
source-dir="tests/stats"
main="checker.f90"
