name = 'fortsa'
version = '0.0.1'
maintainer = 'fortsa contributors'
license = 'BSD 3- Clause Check LINCENSE file'
author = 'fortsa contributors'
categories = 'time series analysis'
copyright = "2014-2021 fortsa contributors"

[build]
auto-examples = false
auto-executables = false
auto-tests = false

[dev-dependencies]
forlab = { git = "https://github.com/zoziha/forlab", branch = "feature/fypp_src" }

[library]
source-dir="src"

# ============================ tests ===========================================
## [model] tests
[[test]]
name="model_ar"
source-dir="tests/model"
main="test_model_ar.f90"
[[test]]
name="model_ar2"
source-dir="tests/model"
main="test_model_ar2.f90"
[[test]]
name="model_arima"
source-dir="tests/model"
main="test_model_arima.f90"
[[test]]
name="model_autoarima"
source-dir="tests/model"
main="test_model_autoarima.f90"
[[test]]
name="model_autoarima2"
source-dir="tests/model"
main="test_model_autoarima2.f90"
[[test]]
name="model_autoarima3"
source-dir="tests/model"
main="test_model_autoarima3.f90"
[[test]]
name="model_dwt"
source-dir="tests/model"
main="test_model_dwt.f90"
# [[test]]
# name="model_misc"
# source-dir="tests/model"
# main="test_model_misc.f90"
[[test]]
name="model_sarima"
source-dir="tests/model"
main="test_model_sarima.f90"
[[test]]
name="model_sarimax"
source-dir="tests/model"
main="test_model_sarimax.f90"
[[test]]
name="model_sarimax2"
source-dir="tests/model"
main="test_model_sarimax2.f90"
[[test]]
name="model_sarimax3"
source-dir="tests/model"
main="test_model_sarimax3.f90"

## [stats] tests
[[test]]
name="stats_acf"
source-dir="tests/stats"
main="test_stats_acf.f90"
[[test]]
name="stats_pacf"
source-dir="tests/stats"
main="test_stats_pacf.f90"

