name = 'fortsa'
version = '0.0.3'
maintainer = 'fortsa contributors'
license = 'BSD 3- Clause'
author = '左志华'
categories = 'time series analysis'
copyright = "2021 fortsa contributors"

[build]
auto-examples = false
auto-executables = false
auto-tests = false

[dependencies]
ctsa = { git="https://github.com/zoziha/ctsa", branch="ctsa-fpm" }

[dev-dependencies]
## `stdlib` inside `forlab` dependencies
forlab = { git = "https://github.com/zoziha/forlab" }
test-drive = { git="https://github.com/fortran-lang/test-drive" }

[library]
source-dir="src"

# ============================ tests ===========================================
## [dwt] tests
[[test]]
name="dwt"
source-dir="test/dwt"
main="test_dwt_dwt.f90"

## [model] tests
[[test]]
name="model"
source-dir="test/model"
main="checker.f90"
[[test]]
name="model_arima"
source-dir="test/model"
main="test_model_arima.f90"

## [stats] tests
[[test]]
name="stats"
source-dir="test/stats"
main="checker.f90"
