name = 'fortsa'
version = '0.1.2'
maintainer = '左志华(zuo.zhihua@qq.com)'
license = 'BSD-3-Clause'
author = '左志华'
categories = ['Time series analysis', 'Fortran-bindings']
copyright = "2021-2022, 左志华"

[build]
auto-examples = false
auto-executables = false
auto-tests = false

[dependencies]
ctsa = { path = "ctsa" }

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive" }

[[test]]
name = "dwt"
source-dir = "test/dwt"
main = "checker.f90"

[[test]]
name = "model"
source-dir = "test/model"
main = "checker.f90"

[[test]]
name = "stats"
source-dir = "test/stats"
main = "checker.f90"
