[book]
authors = ["fortsa contributors"]
language = "zh"
multilingual = false
src = "src"
title = "fortsa api documents"

[output.html]
git-repository-url = "https://github.com/zoziha/fortsa/tree/main/"
edit-url-template = "https://github.com/zoziha/fortsa/edit/main/{path}"